#define DEFAULT_PETROL_CARS_NUM 2320000
#define DEFAULT_ELECTRIC_CARS_NUM 1261

#define DEFAULT_AFTER_PETROL_PERCENTAGE 99.7
#define DEFAULT_AFTER_ELECTRIC_PERCENTAGE 10.0
#define DEFAULT_LENGTH 20.0

#define SIM_START 0.0

#define TOO_OLD_PETROL_CAR 0.97
#define TOO_OLD_ELECTRIC_CAR 0.92
#define TOO_OLD_BATTERY 0.11

#define CO2_NEW_PETROL 1
#define CO2_NEW_ELECTRIC 1
#define CO2_NEW_BATTERY 1

#define INVALID_ARGUMENT 1
#define INVALID_RANGE 2
#define INVALID_VALUE 3


