#define DEFAULT_PETROL_CARS_NUM 2320347
#define DEFAULT_ELECTRIC_CARS_NUM 1261

#define DEFAULT_AFTER_PETROL_PERCENTAGE 98.7
#define DEFAULT_AFTER_ELECTRIC_PERCENTAGE 10.0
#define DEFAULT_LENGTH 20.0

#define SIM_START 0.0

#define INVALID_ARGUMENT 1
#define INVALID_RANGE 2
#define INVALID_VALUE 3


